### ISSUE TITLE
Use namespace labels to limit action on a SqlHost

### ISSUE THREAD

**Issue by NoUseFreak** [stenic/sql-operator#45]
```yaml
apiVersion: stenic.io/v1alpha1
kind: SqlHost
metadata:
  name: example-host
spec:
  engine: Mysql
  dsn: sqloperator:xxxxxxxxxxx@tcp(192.168.1.123:3306)/
  namespaceSelector:
    matchLabels:
      sql-operator/example-host: example-host

```

```yaml
apiVersion: v1
kind: Namespace
metadata:
  labels:
    sql-operator/example-host: example-host
  name: my-project
spec:
```

SqlDatabase/SqlUser/SqlGrant can only be created if the namespace has the required labels
